const enfermeiroHospitalar = [
  {
    id: "enf_hosp_simplificada",
    nome: "Evolução Simplificada",
    descricao: "Modelo resumido de evolução de enfermagem",
    grupos: [
      {
        titulo: "Dados Subjetivos",
        campo: "dados_subjetivos",
        opcoes: [
          "Paciente refere melhora",
          "Paciente refere quadro inalterado",
          "Paciente refere piora",
          "Paciente sem queixas",
          "Refere dor (localizar / EVA: ___)",
          "Refere dispneia",
          "Refere náuseas",
          "Aceitação alimentar boa",
          "Aceitação alimentar parcial",
          "Aceitação alimentar ruim",
          "Sono preservado",
          "Insônia / sono fragmentado",
        ],
      },
      {
        titulo: "Neurológico",
        campo: "neurologico",
        opcoes: [
          "BEG, consciente, orientado, colaborativo",
          "REG, consciente, orientado",
          "MEG, responsivo a estímulos",
          "MEG, não responsivo a estímulos",
          "Sonolento, responsivo ao chamado",
          "Confuso, desorientado",
          "Agitado",
          "Sedado",
          "Analgesiado",
          "Inconsciente sem resposta",
          "Glasgow 15",
          "Glasgow ___",
          "Pupilas isocóricas e fotorreagentes",
          "Sem déficit motor",
          "Com déficit motor",
          "Contenção mecânica em uso",
        ],
      },
      {
        titulo: "Medicações em Uso",
        campo: "medicacoes",
        opcoes: [
          "Antibiótico",
          "Cisatracurio",
          "Dobutamina",
          "Dopamina",
          "Dormonid",
          "Fentanil",
          "Ketamina",
          "Morfina",
          "Noradrenalina",
          "Precedex",
          "Propofol",
        ],
      },
      {
        titulo: "Respiratório",
        campo: "respiratorio",
        opcoes: [
          "ARP: MV+ sem RA bilateralmente",
          "ARP: MV+ com estertores crepitantes",
          "ARP: MV+ com sibilos",
          "ARP: MV+ com roncos",
          "ARP: MV diminuído em base D",
          "ARP: MV diminuído em base E",
          "ARP: MV diminuído bilateralmente",
          "Eupneico em ar ambiente",
          "Dispneico",
          "Taquipneico",
          "Em uso de O₂ por cateter nasal — ___L/min",
          "Em uso de O₂ por máscara de Venturi — FiO₂ ___%",
          "Em uso de O₂ por máscara não reinalante — ___L/min",
          "Em uso de O₂ por máscara com reservatório",
          "Em ventilação não invasiva (VNI)",
          "Em ventilação mecânica invasiva",
          "SatO₂ ___% em ar ambiente",
          "SatO₂ ___% com O₂ suplementar",
        ],
      },
      {
        titulo: "Cardiovascular",
        campo: "cardiovascular",
        opcoes: [
          "ACV: BRNF 2T sem sopros",
          "ACV: presença de sopro",
          "ACV: bulhas arrítmicas",
          "Hemodinamicamente estável",
          "SSVV estáveis",
          "PA estável (___x___mmHg)",
          "PA elevada (___x___mmHg)",
          "Hipotensão (___x___mmHg)",
          "FC normal (___bpm)",
          "Taquicárdico (FC: ___bpm)",
          "Bradicárdico (FC: ___bpm)",
          "Afebril (Tax: ___°C)",
          "Pico febril (___°C)",
          "Perfusão periférica adequada (TEC < 3s)",
          "Perfusão periférica lentificada",
        ],
      },
      {
        titulo: "Abdome",
        campo: "abdome",
        opcoes: [
          "Abdome flácido, indolor, RHA+",
          "Abdome globoso, flácido, indolor",
          "Abdome globoso por adiposidade",
          "Abdome distendido",
          "Abdome doloroso à palpação",
          "RHA diminuídos",
          "RHA ausentes",
        ],
      },
      {
        titulo: "Dieta",
        campo: "dieta",
        opcoes: [
          "Dieta via oral — {livre|pastosa|líquida|branda|hipossódica|para diabético|hipercalórica/hiperproteica|laxante}",
          "SNE {em uso — dieta enteral|fechada|em aspiração sem resíduo|em aspiração com resíduo — ___mL}",
          "SNG {em uso — dieta enteral|fechada|em aspiração sem resíduo|em aspiração com resíduo — ___mL}",
          "Dieta enteral por {gastrostomia|jejunostomia}",
          "Nutrição parenteral total (NPT)",
          "Dieta zero",
          "Aceitação da dieta: {boa|parcial|recusa alimentar}",
        ],
      },
      {
        titulo: "Pele",
        campo: "pele",
        opcoes: [
          "Corado, hidratado, acianótico, anictérico",
          "Descorado (___/4+)",
          "Desidratado (___/4+)",
          "Ictérico (___/4+)",
          "Pele íntegra",
          "Presença de lesão por pressão",
          "Curativo limpo e seco",
          "Curativo com sinais flogísticos",
          "Ferida operatória limpa e seca",
        ],
      },
      {
        titulo: "Extremidades",
        campo: "extremidades",
        opcoes: [
          "MMSS sem edema",
          "MMSS com edema (___/4+)",
          "MMII sem edema",
          "MMII com edema (___/4+)",
          "Panturrilhas livres",
        ],
      },
      {
        titulo: "Dispositivos",
        campo: "dispositivos",
        opcoes: [
          "AVP pérvio, sem sinais flogísticos",
          "AVP pérvio, com sinais flogísticos",
          "CVC sem sinais flogísticos",
          "CVC com sinais flogísticos",
          "Cateter de hemodiálise sem sinais flogísticos",
          "Cateter de hemodiálise com sinais flogísticos",
          "PICC sem sinais flogísticos",
          "PICC com sinais flogísticos",
          "Permcath sem sinais flogísticos",
          "Permcath com sinais flogísticos",
        ],
      },
      {
        titulo: "Eliminações Fisiológicas",
        campo: "eliminacoes_fisiologicas",
        opcoes: [
          "Diurese presente, espontânea e {normal|concentrada}",
          "Diurese presente e espontânea em fraldas",
          "Diurese presente por SVD e {normal|concentrada|colúria|hematúrica|piúria}",
          "Anúrico",
          "Evacuações presentes e normais",
          "Evacuações diarreicas",
          "Melena",
          "Evacuações ausentes há ___dias",
        ],
      },
      {
        titulo: "Conduta de Enfermagem",
        campo: "conduta",
        opcoes: [
          "Cuidados de enfermagem mantidos",
          "Medicação administrada conforme prescrição",
          "Sinais vitais monitorizados",
          "Curativo realizado",
          "Mudança de decúbito realizada",
          "Orientações ao paciente e familiares",
          "Comunicado equipe médica",
          "Higiene corporal realizada",
          "Controle de balanço hídrico",
        ],
      },
      {
        titulo: "Seguimento",
        campo: "seguimento",
        opcoes: [
          "Segue aos cuidados da equipe multiprofissional",
          "Aguardando vaga em enfermaria clínica",
          "Aguardando vaga em UTI",
          "Aguardando ambulância para transferência",
        ],
      },
    ],
  },
  {
    id: "enf_hosp_completa",
    nome: "Evolução Completa",
    descricao: "Modelo completo de evolução de enfermagem hospitalar",
    grupos: [
      {
        titulo: "Dados Subjetivos",
        campo: "dados_subjetivos",
        opcoes: [
          "Paciente refere melhora",
          "Paciente refere quadro inalterado",
          "Paciente refere piora",
          "Paciente sem queixas",
          "Refere dor (localizar / EVA: ___)",
          "Refere dispneia",
          "Refere náuseas / vômitos",
          "Aceitação alimentar boa",
          "Aceitação alimentar parcial",
          "Aceitação alimentar ruim",
          "Sono preservado",
          "Insônia / sono fragmentado",
        ],
      },
      {
        titulo: "Neurológico",
        campo: "neurologico",
        opcoes: [
          "BEG, consciente, orientado, colaborativo",
          "REG, consciente, orientado",
          "MEG, responsivo a estímulos",
          "MEG, não responsivo a estímulos",
          "Sonolento, responsivo ao chamado",
          "Confuso, desorientado",
          "Agitado",
          "Sedado",
          "Analgesiado",
          "Inconsciente sem resposta",
          "Glasgow 15",
          "Glasgow ___",
          "Pupilas isocóricas e fotorreagentes",
          "Sem déficit motor",
          "Com déficit motor",
          "Contenção mecânica em uso",
        ],
      },
      {
        titulo: "Medicações em Uso",
        campo: "medicacoes",
        opcoes: [
          "Antibiótico",
          "Cisatracurio",
          "Dobutamina",
          "Dopamina",
          "Dormonid",
          "Fentanil",
          "Ketamina",
          "Morfina",
          "Noradrenalina",
          "Precedex",
          "Propofol",
        ],
      },
      {
        titulo: "Respiratório",
        campo: "respiratorio",
        opcoes: [
          "ARP: MV+ sem RA bilateralmente",
          "ARP: MV+ com estertores crepitantes",
          "ARP: MV+ com sibilos",
          "ARP: MV+ com roncos",
          "ARP: MV diminuído em base D",
          "ARP: MV diminuído em base E",
          "ARP: MV diminuído bilateralmente",
          "Eupneico em ar ambiente",
          "Dispneico",
          "Taquipneico",
          "Em uso de O₂ por cateter nasal — ___L/min",
          "Em uso de O₂ por máscara de Venturi — FiO₂ ___%",
          "Em uso de O₂ por máscara não reinalante — ___L/min",
          "Em uso de O₂ por máscara com reservatório",
          "Em ventilação não invasiva (VNI)",
          "Em ventilação mecânica invasiva",
          "SatO₂ ___% em ar ambiente",
          "SatO₂ ___% com O₂ suplementar",
        ],
      },
      {
        titulo: "Cardiovascular",
        campo: "cardiovascular",
        opcoes: [
          "ACV: BRNF 2T sem sopros",
          "ACV: presença de sopro",
          "ACV: bulhas arrítmicas",
          "Hemodinamicamente estável",
          "SSVV estáveis",
          "PA estável (___x___mmHg)",
          "PA elevada (___x___mmHg)",
          "Hipotensão (___x___mmHg)",
          "FC normal (___bpm)",
          "Taquicárdico (FC: ___bpm)",
          "Bradicárdico (FC: ___bpm)",
          "Afebril (Tax: ___°C)",
          "Pico febril (___°C)",
          "Perfusão periférica adequada (TEC < 3s)",
          "Perfusão periférica lentificada",
        ],
      },
      {
        titulo: "Abdome",
        campo: "abdome",
        opcoes: [
          "Abdome flácido, indolor, RHA+",
          "Abdome globoso, flácido, indolor",
          "Abdome globoso por adiposidade",
          "Abdome distendido",
          "Abdome doloroso à palpação",
          "RHA diminuídos",
          "RHA ausentes",
        ],
      },
      {
        titulo: "Dieta",
        campo: "dieta",
        opcoes: [
          "Dieta via oral — {livre|pastosa|líquida|branda|hipossódica|para diabético|hipercalórica/hiperproteica|laxante}",
          "SNE {em uso — dieta enteral|fechada|em aspiração sem resíduo|em aspiração com resíduo — ___mL}",
          "SNG {em uso — dieta enteral|fechada|em aspiração sem resíduo|em aspiração com resíduo — ___mL}",
          "Dieta enteral por {gastrostomia|jejunostomia}",
          "Nutrição parenteral total (NPT)",
          "Dieta zero",
          "Aceitação da dieta: {boa|parcial|recusa alimentar}",
        ],
      },
      {
        titulo: "Eliminações Fisiológicas",
        campo: "eliminacoes_fisiologicas",
        opcoes: [
          "Diurese presente, espontânea e {normal|concentrada}",
          "Diurese presente e espontânea em fraldas",
          "Diurese presente por SVD e {normal|concentrada|colúria|hematúrica|piúria}",
          "Anúrico",
          "Evacuações presentes e normais",
          "Evacuações diarreicas",
          "Melena",
          "Evacuações ausentes há ___dias",
        ],
      },
      {
        titulo: "Pele",
        campo: "pele",
        opcoes: [
          "Corado, hidratado, acianótico, anictérico",
          "Descorado (___/4+)",
          "Desidratado (___/4+)",
          "Ictérico (___/4+)",
          "Pele íntegra",
          "Presença de lesão por pressão",
          "Curativo limpo e seco",
          "Curativo com sinais flogísticos",
          "Ferida operatória limpa e seca",
          "FO com sinais flogísticos",
        ],
      },
      {
        titulo: "Extremidades",
        campo: "extremidades",
        opcoes: [
          "MMSS sem edema",
          "MMSS com edema (___/4+)",
          "MMII sem edema",
          "MMII com edema (___/4+)",
          "Panturrilhas livres",
        ],
      },
      {
        titulo: "Dispositivos",
        campo: "dispositivos",
        opcoes: [
          "AVP pérvio, sem sinais flogísticos",
          "AVP pérvio, com sinais flogísticos",
          "CVC sem sinais flogísticos",
          "CVC com sinais flogísticos",
          "Cateter de hemodiálise sem sinais flogísticos",
          "Cateter de hemodiálise com sinais flogísticos",
          "PICC sem sinais flogísticos",
          "PICC com sinais flogísticos",
          "Permcath sem sinais flogísticos",
          "Permcath com sinais flogísticos",
          "Acesso venoso central sem sinais de infecção",
          "Dreno",
        ],
      },
      {
        titulo: "Escalas de Risco",
        campo: "escalas",
        opcoes: [
          "Escala de Braden: risco baixo",
          "Escala de Braden: risco moderado",
          "Escala de Braden: risco alto",
          "Escala de Morse: risco de queda baixo",
          "Escala de Morse: risco de queda alto",
        ],
      },
      {
        titulo: "Diagnóstico de Enfermagem",
        campo: "diagnostico_enfermagem",
        opcoes: [
          "Risco de infecção relacionado a procedimento invasivo",
          "Integridade da pele prejudicada",
          "Risco de lesão por pressão",
          "Mobilidade física prejudicada",
          "Padrão respiratório ineficaz",
          "Troca de gases prejudicada",
          "Débito cardíaco diminuído",
          "Volume de líquidos deficiente",
          "Volume de líquidos excessivo",
          "Nutrição desequilibrada: menor que as necessidades",
          "Dor aguda",
          "Risco de queda",
          "Confusão aguda",
          "Déficit no autocuidado",
          "Ansiedade",
        ],
      },
      {
        titulo: "Intervenções de Enfermagem",
        campo: "conduta",
        opcoes: [
          "Mantido cuidados de enfermagem conforme prescrição",
          "Monitorização contínua de sinais vitais",
          "Administração de medicamentos conforme prescrição médica",
          "Realizado curativo",
          "Mudança de decúbito a cada 2 horas",
          "Cabeceira elevada a 30-45°",
          "Aspiração de vias aéreas conforme necessidade",
          "Controle rigoroso de balanço hídrico",
          "Cuidados com dispositivos invasivos",
          "Troca de acesso venoso periférico",
          "Higiene corporal no leito",
          "Estimulação de deambulação",
          "Orientações ao paciente e familiares",
          "Comunicado equipe médica",
          "Escala de dor avaliada e registrada",
          "Profilaxia de lesão por pressão mantida",
          "Grades elevadas para segurança",
        ],
      },
      {
        titulo: "Seguimento",
        campo: "seguimento",
        opcoes: [
          "Segue aos cuidados da equipe multiprofissional",
          "Aguardando vaga em enfermaria clínica",
          "Aguardando vaga em UTI",
          "Aguardando ambulância para transferência",
        ],
      },
    ],
  },
  {
    id: "enf_hosp_uti",
    nome: "Evolução UTI",
    descricao: "Modelo de enfermagem para terapia intensiva",
    grupos: [
      {
        titulo: "Dados Subjetivos",
        campo: "dados_subjetivos",
        opcoes: [
          "Paciente refere melhora",
          "Paciente refere quadro inalterado",
          "Paciente refere piora",
          "Paciente sem queixas",
          "Refere dor (localizar / EVA: ___)",
          "Refere dispneia",
          "Refere náuseas / vômitos",
          "Aceitação alimentar boa",
          "Aceitação alimentar parcial",
          "Aceitação alimentar ruim",
          "Sono preservado",
          "Insônia / sono fragmentado",
        ],
      },
      {
        titulo: "Neurológico / Nível de Consciência",
        campo: "neurologico",
        opcoes: [
          "BEG, consciente, orientado, colaborativo",
          "REG, consciente, orientado",
          "MEG, responsivo a estímulos",
          "MEG, não responsivo a estímulos",
          "Sonolento, responsivo ao chamado",
          "Confuso, desorientado",
          "Agitado",
          "Consciente, orientado, colaborativo",
          "Sonolento, responsivo ao estímulo verbal",
          "Sedado (RASS: ___)",
          "Analgesiado",
          "Inconsciente sem resposta",
          "Coma (Glasgow: ___)",
          "Pupilas isocóricas e fotorreagentes",
          "Pupilas anisocóricas",
          "Agitação psicomotora",
          "Delirium (CAM-ICU positivo)",
          "Contenção mecânica em uso",
        ],
      },
      {
        titulo: "Medicações em Uso",
        campo: "medicacoes",
        opcoes: [
          "Antibiótico",
          "Cisatracurio",
          "Dobutamina",
          "Dopamina",
          "Dormonid",
          "Fentanil",
          "Ketamina",
          "Morfina",
          "Noradrenalina",
          "Precedex",
          "Propofol",
        ],
      },
      {
        titulo: "Sistema Respiratório",
        campo: "respiratorio",
        opcoes: [
          "ARP: MV+ sem RA bilateralmente",
          "ARP: MV+ com estertores crepitantes",
          "ARP: MV+ com sibilos",
          "ARP: MV+ com roncos",
          "ARP: MV diminuído em base D",
          "ARP: MV diminuído em base E",
          "ARP: MV diminuído bilateralmente",
          "Eupneico em ar ambiente",
          "Dispneico",
          "Taquipneico",
          "VM invasiva — modo/parâmetros: ___",
          "VM não invasiva (VNI)",
          "Em uso de O₂ por cateter nasal — ___L/min",
          "Em uso de O₂ por máscara de Venturi — FiO₂ ___%",
          "Em uso de O₂ por máscara não reinalante — ___L/min",
          "Em uso de O₂ por máscara com reservatório",
          "Traqueostomia",
          "Em desmame ventilatório",
          "Pós-extubação",
          "Secreção traqueal: clara / espessa / purulenta",
          "Aspiração de VAS realizada",
          "SatO₂ ___% em ar ambiente",
          "SatO₂ ___% com O₂ suplementar",
        ],
      },
      {
        titulo: "Hemodinâmica / Cardiovascular",
        campo: "cardiovascular",
        opcoes: [
          "ACV: BRNF 2T sem sopros",
          "ACV: presença de sopro",
          "ACV: bulhas arrítmicas",
          "Hemodinamicamente estável sem DVA",
          "Em uso de DVA",
          "Em desmame de DVA",
          "Ritmo sinusal ao monitor",
          "Arritmia",
          "SSVV estáveis",
          "PA estável (___x___mmHg)",
          "PA elevada (___x___mmHg)",
          "Hipotensão (___x___mmHg)",
          "FC normal (___bpm)",
          "Taquicárdico (FC: ___bpm)",
          "Bradicárdico (FC: ___bpm)",
          "Afebril (Tax: ___°C)",
          "Pico febril (___°C)",
          "Perfusão periférica adequada (TEC < 3s)",
          "Perfusão periférica lentificada",
          "Acesso venoso central pérvio, sem sinais de infecção",
          "PAI monitorizada",
          "PVC: ___cmH₂O",
        ],
      },
      {
        titulo: "Abdome",
        campo: "abdome",
        opcoes: [
          "Abdome flácido, indolor, RHA+",
          "Abdome globoso, flácido, indolor",
          "Abdome globoso por adiposidade",
          "Abdome distendido",
          "Abdome doloroso à palpação",
          "RHA diminuídos",
          "RHA ausentes",
        ],
      },
      {
        titulo: "Dieta",
        campo: "dieta",
        opcoes: [
          "Dieta via oral — {livre|pastosa|líquida|branda}",
          "SNE {em uso — dieta enteral|fechada|em aspiração sem resíduo|em aspiração com resíduo — ___mL}",
          "SNG {em uso — dieta enteral|fechada|em aspiração sem resíduo|em aspiração com resíduo — ___mL}",
          "Dieta enteral por {gastrostomia|jejunostomia}",
          "SNE: dieta enteral com boa tolerância",
          "SNE: resíduo gástrico elevado",
          "Nutrição parenteral total (NPT)",
          "Dieta zero",
          "Aceitação da dieta: {boa|parcial|recusa alimentar}",
        ],
      },
      {
        titulo: "Eliminações Fisiológicas",
        campo: "eliminacoes_fisiologicas",
        opcoes: [
          "Diurese presente, espontânea e {normal|concentrada}",
          "Diurese presente e espontânea em fraldas",
          "Diurese presente por SVD e {normal|concentrada|colúria|hematúrica|piúria}",
          "Anúrico",
          "Evacuações presentes e normais",
          "Evacuações diarreicas",
          "Melena",
          "Evacuações ausentes há ___dias",
        ],
      },
      {
        titulo: "Pele",
        campo: "pele",
        opcoes: [
          "Corado, hidratado, acianótico, anictérico",
          "Descorado (___/4+)",
          "Desidratado (___/4+)",
          "Ictérico (___/4+)",
          "Pele íntegra",
          "Presença de lesão por pressão",
          "Curativo limpo e seco",
          "Curativo com sinais flogísticos",
          "Ferida operatória limpa e seca",
          "FO / curativo",
        ],
      },
      {
        titulo: "Extremidades",
        campo: "extremidades",
        opcoes: [
          "MMSS sem edema",
          "MMSS com edema (___/4+)",
          "MMII sem edema",
          "MMII com edema (___/4+)",
          "Panturrilhas livres",
        ],
      },
      {
        titulo: "Dispositivos",
        campo: "dispositivos",
        opcoes: [
          "AVP pérvio, sem sinais flogísticos",
          "AVP pérvio, com sinais flogísticos",
          "CVC sem sinais flogísticos",
          "CVC com sinais flogísticos",
          "Cateter de hemodiálise sem sinais flogísticos",
          "Cateter de hemodiálise com sinais flogísticos",
          "PICC sem sinais flogísticos",
          "PICC com sinais flogísticos",
          "Permcath sem sinais flogísticos",
          "Permcath com sinais flogísticos",
          "Dreno",
          "SVD pérvio",
          "Cateter arterial pérvio",
          "Dreno torácico oscilante",
        ],
      },
      {
        titulo: "Segurança",
        campo: "seguranca",
        opcoes: [
          "Grades elevadas",
          "Cabeceira elevada 30-45°",
          "Mudança de decúbito realizada",
          "Contenção mecânica em uso",
          "Escala de Braden: ___",
          "Escala de Morse: ___",
        ],
      },
      {
        titulo: "Intervenções de Enfermagem",
        campo: "conduta",
        opcoes: [
          "Monitorização multiparamétrica contínua",
          "Controle rigoroso de BH",
          "Administração de medicamentos conforme prescrição",
          "Controle de DVA conforme protocolo",
          "Cuidados com VM (circuito, umidificação, cuff)",
          "Aspiração de VAS SN",
          "Higiene oral com clorexidina",
          "Banho no leito",
          "Mudança de decúbito 2/2h",
          "Curativo de CVC / cateter arterial",
          "Curativo de FO / lesão",
          "Avaliação de escalas (Braden, Morse, RASS, Glasgow)",
          "Protocolo de prevenção de LPP mantido",
          "Profilaxia de TVP mantida",
          "Bundle de prevenção de PAV mantido",
          "Bundle de prevenção de ITU mantido",
          "Bundle de prevenção de IPCS mantido",
          "Comunicação com equipe multidisciplinar",
          "Orientações aos familiares no horário de visita",
        ],
      },
      {
        titulo: "Seguimento",
        campo: "seguimento",
        opcoes: [
          "Segue aos cuidados da equipe multiprofissional",
          "Aguardando vaga em enfermaria clínica",
          "Aguardando vaga em UTI",
          "Aguardando ambulância para transferência",
        ],
      },
    ],
  },
];

export default enfermeiroHospitalar;