const medicoHospitalar = [
  {
    id: "med_hosp_simplificada",
    nome: "Evolução Simplificada",
    descricao: "Modelo resumido para evolução diária rápida",
    grupos: [
      {
        titulo: "Estado Geral",
        campo: "estado_geral",
        opcoes: [
          "Paciente refere melhora clínica",
          "Paciente refere quadro inalterado",
          "Paciente refere piora clínica",
          "Paciente sem queixas",
          "Refere dor (EVA: ___)",
          "Aceitação alimentar boa",
          "Aceitação alimentar parcial",
          "Aceitação alimentar ruim",
          "Em jejum",
          "Diurese presente e clara",
          "Diurese concentrada",
          "Evacuação presente",
          "Constipação há ___dias",
          "Sono preservado",
          "Insônia / sono fragmentado",
        ],
      },
      {
        titulo: "Neurológico",
        campo: "neurologico",
        opcoes: [
          "BEG, lúcido, orientado, colaborativo",
          "REG, lúcido, orientado",
          "MEG, responsivo a estímulos",
          "MEG, não responsivo a estímulos",
          "Sonolento, responsivo ao chamado",
          "Confuso, desorientado",
          "Sedado",
          "Analgesiado",
          "Inconsciente sem resposta",
          "Glasgow 15",
          "Glasgow ___",
          "Pupilas isocóricas e fotorreagentes",
          "Sem déficit motor focal",
          "Com déficit motor",
        ],
      },
      {
        titulo: "Respiratório",
        campo: "respiratorio",
        opcoes: [
          "ARP: MV+ sem RA bilateralmente",
          "ARP: MV+ com estertores crepitantes",
          "ARP: MV+ com sibilos",
          "ARP: MV+ com roncos",
          "ARP: MV diminuído em base D",
          "ARP: MV diminuído em base E",
          "ARP: MV diminuído bilateralmente",
          "Eupneico em ar ambiente",
          "Dispneico",
          "Taquipneico",
          "Em uso de O₂ por cateter nasal — ___L/min",
          "Em uso de O₂ por máscara de Venturi — FiO₂ ___%",
          "Em uso de O₂ por máscara não reinalante — ___L/min",
          "Em uso de O₂ por máscara com reservatório",
          "Em ventilação não invasiva (VNI)",
          "Em ventilação mecânica invasiva",
          "SatO₂ ___% em ar ambiente",
          "SatO₂ ___% com O₂ suplementar",
        ],
      },
      {
        titulo: "Cardiovascular",
        campo: "cardiovascular",
        opcoes: [
          "ACV: BRNF 2T sem sopros",
          "ACV: presença de sopro",
          "ACV: bulhas arrítmicas",
          "Hemodinamicamente estável",
          "PA estável (___x___mmHg)",
          "PA elevada (___x___mmHg)",
          "Hipotensão (___x___mmHg)",
          "FC normal (___bpm)",
          "Taquicárdico (FC: ___bpm)",
          "Bradicárdico (FC: ___bpm)",
          "Afebril (Tax: ___°C)",
          "Pico febril nas últimas 24h (___°C)",
          "Perfusão periférica adequada (TEC < 3s)",
          "Perfusão periférica lentificada",
        ],
      },
      {
        titulo: "Abdome",
        campo: "abdome",
        opcoes: [
          "Abdome: plano, flácido, indolor, RHA+",
          "Abdome: globoso, flácido, indolor",
          "Abdome: distendido",
          "Abdome: doloroso à palpação",
          "Abdome: RHA diminuídos",
          "Abdome: RHA ausentes",
        ],
      },
      {
        titulo: "Dieta",
        campo: "dieta",
        opcoes: [
          "Dieta via oral — livre",
          "Dieta via oral — pastosa",
          "Dieta via oral — líquida",
          "Dieta via oral — branda",
          "Dieta via oral — hipossódica",
          "Dieta via oral — para diabético",
          "Dieta via oral — hipercalórica/hiperproteica",
          "Dieta via oral — laxante",
          "Dieta enteral por SNE",
          "Dieta enteral por gastrostomia",
          "Dieta enteral por jejunostomia",
          "Nutrição parenteral total (NPT)",
          "Em jejum",
          "Boa aceitação da dieta",
          "Aceitação parcial da dieta",
          "Recusa alimentar",
          "Dieta suspensa (motivo: ___)",
        ],
      },
      {
        titulo: "Pele / Extremidades / Dispositivos",
        campo: "pele_extremidades",
        opcoes: [
          "Corado, hidratado, acianótico, anictérico",
          "Descorado (___/4+)",
          "Desidratado (___/4+)",
          "Ictérico (___/4+)",
          "MMSS: sem edema",
          "MMSS: edema (___/4+)",
          "MMII: sem edema, sem sinais de TVP",
          "MMII: edema bilateral (___/4+)",
          "MMII: edema unilateral D/E",
          "Panturrilhas livres",
          "Ferida operatória: limpa e seca",
          "Ferida operatória com sinais flogísticos",
          "Curativo limpo e seco",
          "AVP pérvio, sem sinais flogísticos",
          "AVP pérvio, com sinais flogísticos",
          "CVC sem sinais flogísticos",
          "CVC com sinais flogísticos",
          "Cateter de hemodiálise sem sinais flogísticos",
          "Cateter de hemodiálise com sinais flogísticos",
          "PICC sem sinais flogísticos",
          "PICC com sinais flogísticos",
          "Permcath sem sinais flogísticos",
          "Permcath com sinais flogísticos",
          "Sonda vesical de demora com diurese clara",
          "Sonda nasoentérica em posição",
          "Pele íntegra",
          "Presença de lesão por pressão",
        ],
      },
      {
        titulo: "Conduta",
        campo: "conduta",
        opcoes: [
          "Manutenção da prescrição",
          "Ajuste de prescrição",
          "Solicitar exames de controle",
          "Manter hidratação venosa",
          "Progressão de dieta",
          "Fisioterapia mantida",
          "Profilaxia de TVP mantida",
          "Preparo para alta hospitalar",
          "Manter internação",
        ],
      },
    ],
  },
  {
    id: "med_hosp_completa",
    nome: "Evolução Completa",
    descricao: "Modelo completo com todos os campos detalhados",
    grupos: [
      {
        titulo: "Estado do Paciente",
        campo: "estado_geral",
        opcoes: [
          "Paciente refere melhora clínica",
          "Paciente refere quadro inalterado",
          "Paciente refere piora clínica",
          "Paciente sem queixas",
          "Refere dor (EVA: ___)",
          "Refere dispneia",
          "Refere náuseas",
          "Aceitação alimentar boa",
          "Aceitação alimentar parcial",
          "Aceitação alimentar ruim",
          "Em jejum",
          "Diurese presente e clara",
          "Diurese concentrada",
          "Evacuação presente",
          "Constipação há ___dias",
          "Sono preservado",
          "Insônia / sono fragmentado",
        ],
      },
      {
        titulo: "Neurológico",
        campo: "neurologico",
        opcoes: [
          "BEG, lúcido, orientado, colaborativo",
          "REG, lúcido, orientado",
          "MEG, responsivo a estímulos",
          "MEG, não responsivo a estímulos",
          "Sonolento, responsivo ao chamado",
          "Confuso, desorientado",
          "Sedado",
          "Analgesiado",
          "Inconsciente sem resposta",
          "Glasgow 15",
          "Glasgow ___",
          "Pupilas isocóricas e fotorreagentes",
          "Sem déficit motor focal",
          "Com déficit motor",
        ],
      },
      {
        titulo: "Respiratório",
        campo: "respiratorio",
        opcoes: [
          "ARP: MV+ sem RA bilateralmente",
          "ARP: MV+ com estertores crepitantes",
          "ARP: MV+ com sibilos",
          "ARP: MV+ com roncos",
          "ARP: MV diminuído em base D",
          "ARP: MV diminuído em base E",
          "ARP: MV diminuído bilateralmente",
          "Eupneico em ar ambiente",
          "Dispneico",
          "Taquipneico",
          "Em uso de O₂ por cateter nasal — ___L/min",
          "Em uso de O₂ por máscara de Venturi — FiO₂ ___%",
          "Em uso de O₂ por máscara não reinalante — ___L/min",
          "Em uso de O₂ por máscara com reservatório",
          "Em ventilação não invasiva (VNI)",
          "Em ventilação mecânica invasiva",
          "SatO₂ ___% em ar ambiente",
          "SatO₂ ___% com O₂ suplementar",
        ],
      },
      {
        titulo: "Cardiovascular",
        campo: "cardiovascular",
        opcoes: [
          "ACV: BRNF 2T sem sopros",
          "ACV: presença de sopro",
          "ACV: bulhas arrítmicas",
          "Hemodinamicamente estável",
          "PA estável (___x___mmHg)",
          "PA instável necessitando DVA (___x___mmHg)",
          "PA elevada (___x___mmHg)",
          "Hipotensão (___x___mmHg)",
          "FC normal (___bpm)",
          "Taquicárdico (FC: ___bpm)",
          "Bradicárdico (FC: ___bpm)",
          "Afebril (Tax: ___°C)",
          "Pico febril nas últimas 24h (___°C)",
          "Perfusão periférica adequada (TEC < 3s)",
          "Perfusão periférica lentificada",
        ],
      },
      {
        titulo: "Abdome",
        campo: "abdome",
        opcoes: [
          "Abdome: plano, flácido, indolor, RHA+",
          "Abdome: globoso, flácido, indolor",
          "Abdome: distendido",
          "Abdome: doloroso à palpação",
          "Abdome: RHA diminuídos",
          "Abdome: RHA ausentes",
        ],
      },
      {
        titulo: "Dieta",
        campo: "dieta",
        opcoes: [
          "Dieta via oral — livre",
          "Dieta via oral — pastosa",
          "Dieta via oral — líquida",
          "Dieta via oral — branda",
          "Dieta via oral — hipossódica",
          "Dieta via oral — para diabético",
          "Dieta via oral — hipercalórica/hiperproteica",
          "Dieta via oral — laxante",
          "Dieta enteral por SNE",
          "Dieta enteral por gastrostomia",
          "Dieta enteral por jejunostomia",
          "Nutrição parenteral total (NPT)",
          "Em jejum",
          "Boa aceitação da dieta",
          "Aceitação parcial da dieta",
          "Recusa alimentar",
          "Dieta suspensa (motivo: ___)",
        ],
      },
      {
        titulo: "Renal / Balanço Hídrico",
        campo: "renal",
        opcoes: [
          "Balanço hídrico positivo",
          "Balanço hídrico negativo",
          "Balanço hídrico equilibrado",
        ],
      },
      {
        titulo: "Pele / Extremidades / Dispositivos",
        campo: "pele_extremidades",
        opcoes: [
          "Corado, hidratado, acianótico, anictérico",
          "Descorado (___/4+)",
          "Desidratado (___/4+)",
          "Ictérico (___/4+)",
          "MMSS: sem edema",
          "MMSS: edema (___/4+)",
          "MMII: sem edema, sem sinais de TVP",
          "MMII: edema bilateral (___/4+)",
          "MMII: edema unilateral D/E",
          "Panturrilhas livres",
          "Ferida operatória: limpa e seca",
          "Ferida operatória com sinais flogísticos",
          "Curativo limpo e seco",
          "AVP pérvio, sem sinais flogísticos",
          "AVP pérvio, com sinais flogísticos",
          "CVC sem sinais flogísticos",
          "CVC com sinais flogísticos",
          "Cateter de hemodiálise sem sinais flogísticos",
          "Cateter de hemodiálise com sinais flogísticos",
          "PICC sem sinais flogísticos",
          "PICC com sinais flogísticos",
          "Permcath sem sinais flogísticos",
          "Permcath com sinais flogísticos",
          "Sonda vesical de demora com diurese clara",
          "Sonda nasoentérica em posição",
          "Pele íntegra",
          "Presença de lesão por pressão",
        ],
      },
      {
        titulo: "Resultados de Exames",
        campo: "exames",
        opcoes: [
          "Exames laboratoriais sem alterações significativas",
          "Hemograma com leucocitose",
          "Hemograma com anemia",
          "PCR elevada",
          "Função renal preservada",
          "Função renal alterada",
          "Eletrólitos dentro da normalidade",
          "Distúrbio eletrolítico",
          "Radiografia de tórax sem alterações agudas",
          "Radiografia de tórax com infiltrado pulmonar",
          "Culturas pendentes",
          "Hemocultura positiva para",
        ],
      },
      {
        titulo: "Conduta",
        campo: "conduta",
        opcoes: [
          "Manutenção da prescrição",
          "Ajuste de antibioticoterapia",
          "Início de antibioticoterapia empírica",
          "Solicitar parecer de",
          "Solicitar exames laboratoriais de controle",
          "Solicitar exame de imagem",
          "Manter hidratação venosa",
          "Progressão de dieta",
          "Manter jejum",
          "Fisioterapia motora e respiratória",
          "Profilaxia de TVP mantida",
          "Controle rigoroso de sinais vitais",
          "Preparo para alta hospitalar",
          "Manter internação para tratamento",
          "Discutir caso em equipe multidisciplinar",
        ],
      },
    ],
  },
  {
    id: "med_hosp_uti",
    nome: "Evolução UTI",
    descricao: "Modelo específico para pacientes em terapia intensiva",
    grupos: [
      {
        titulo: "Neurológico / Nível de Consciência",
        campo: "neurologico",
        opcoes: [
          "Lúcido, orientado, colaborativo",
          "Sonolento, responsivo ao estímulo verbal",
          "Sedado, responsivo ao estímulo doloroso",
          "Sedação contínua (RASS: ___)",
          "Analgesiado",
          "Inconsciente sem resposta",
          "Coma (Glasgow: ___)",
          "Pupilas isocóricas e fotorreagentes",
          "Pupilas anisocóricas",
          "Reflexos de tronco presentes",
          "Agitação psicomotora",
          "Delirium presente (CAM-ICU positivo)",
        ],
      },
      {
        titulo: "Sistema Respiratório",
        campo: "respiratorio",
        opcoes: [
          "Em ventilação mecânica invasiva",
          "Modo ventilatório: VCV",
          "Modo ventilatório: PCV",
          "Modo ventilatório: PSV",
          "FiO₂: ___% / PEEP: ___cmH₂O",
          "SatO₂ ___% em ar ambiente",
          "SatO₂ ___% com O₂ suplementar",
          "Relação P/F adequada (>200)",
          "Relação P/F baixa (<200) — SDRA",
          "Em desmame ventilatório",
          "Teste de respiração espontânea realizado",
          "Extubado com sucesso",
          "Falha de extubação",
          "Em ventilação mecânica não invasiva (VNI)",
          "Em uso de O₂ por cateter nasal — ___L/min",
          "Traqueostomia — em ar ambiente / O₂",
          "ARP: MV+ sem RA",
          "ARP: MV+ com RA",
          "ARP: MV diminuído",
          "Secreção traqueal: clara / espessa / purulenta",
        ],
      },
      {
        titulo: "Sistema Cardiovascular / Hemodinâmica",
        campo: "cardiovascular",
        opcoes: [
          "Hemodinamicamente estável sem DVA",
          "Em uso de noradrenalina (dose: ___mcg/kg/min)",
          "Em uso de dobutamina",
          "Em uso de vasopressina",
          "Desmame de drogas vasoativas em curso",
          "ACV: BRNF 2T sem sopros",
          "ACV: bulhas arrítmicas",
          "Ritmo sinusal ao monitor",
          "Fibrilação atrial",
          "PA estável (___x___mmHg)",
          "PA elevada (___x___mmHg)",
          "Hipotensão (___x___mmHg)",
          "FC normal (___bpm)",
          "Taquicárdico (FC: ___bpm)",
          "Bradicárdico (FC: ___bpm)",
          "Afebril (Tax: ___°C)",
          "Pico febril nas últimas 24h (___°C)",
          "PVC: ___cmH₂O",
          "Perfusão periférica adequada (TEC < 3s)",
          "Perfusão periférica lentificada",
          "Lactato sérico normal",
          "Lactato sérico elevado",
        ],
      },
      {
        titulo: "Função Renal / Balanço Hídrico",
        campo: "renal",
        opcoes: [
          "Diurese > 0,5ml/kg/h",
          "Oligúria (<0,5ml/kg/h)",
          "Anúria",
          "Em terapia de substituição renal (hemodiálise)",
          "Balanço hídrico positivo",
          "Balanço hídrico negativo",
          "Balanço hídrico equilibrado",
          "Creatinina estável",
          "Creatinina em elevação",
          "Eletrólitos dentro da normalidade",
          "Hipercalemia",
          "Hipocalemia",
          "Hipernatremia",
          "Hiponatremia",
        ],
      },
      {
        titulo: "Abdome / Nutrição / Dispositivos",
        campo: "abdome_dispositivos",
        opcoes: [
          "Abdome: flácido, indolor, RHA+",
          "Abdome: distendido, RHA diminuídos",
          "Abdome: dreno com débito",
          "Dieta enteral por SNE — boa tolerância",
          "Dieta enteral — resíduo gástrico elevado",
          "Nutrição parenteral",
          "Jejum",
          "Dieta via oral",
          "Evacuação presente",
          "Constipação há ___dias",
          "Acesso venoso central — sem sinais de infecção",
          "Cateter arterial",
          "Sonda vesical de demora",
          "Dreno torácico — oscilante / sem borbulhamento",
          "Ferida operatória / curativo",
          "Úlcera por pressão",
        ],
      },
      {
        titulo: "Conduta",
        campo: "conduta",
        opcoes: [
          "Manutenção do suporte intensivo",
          "Ajuste de parâmetros ventilatórios",
          "Protocolo de desmame ventilatório",
          "Programar extubação",
          "Ajuste de sedação (alvo RASS: ___)",
          "Despertar diário / férias de sedação",
          "Ajuste de drogas vasoativas",
          "Desmame de DVA",
          "Ajuste de antibioticoterapia",
          "Escalonamento antibiótico",
          "Desescalonamento antibiótico",
          "Solicitação de culturas",
          "Solicitar exames laboratoriais de controle",
          "Solicitar exame de imagem",
          "Controle glicêmico rigoroso",
          "Indicação de terapia renal substitutiva",
          "Profilaxia de TVP",
          "Profilaxia de úlcera de estresse",
          "Mobilização precoce / fisioterapia",
          "Discussão de caso em round multidisciplinar",
          "Comunicação com familiares",
          "Avaliar transferência para enfermaria",
          "Manter cuidados intensivos",
        ],
      },
    ],
  },
];

export default medicoHospitalar;