const medicoAtencaoPrimaria = [
  {
    id: "med_ap_hipertenso",
    nome: "Hipertenso",
    descricao: "Acompanhamento de pacientes hipertensos",
    grupos: [
      {
        titulo: "Queixa Principal",
        campo: "queixa_principal",
        opcoes: [
          "Consulta de rotina",
          "Cefaleia",
          "Tontura",
          "Dispneia aos esforços",
          "Dor torácica",
          "Edema em membros inferiores",
          "Palpitações",
          "Epistaxe",
          "Turvação visual",
          "Assintomático",
        ],
      },
      {
        titulo: "Adesão ao Tratamento",
        campo: "hda",
        opcoes: [
          "Uso regular da medicação anti-hipertensiva",
          "Uso irregular da medicação",
          "Dificuldade em adquirir a medicação",
          "Dieta hipossódica mantida",
          "Dieta inadequada (rica em sódio)",
          "Prática de atividade física regular",
          "Sedentário",
          "Tabagista ativo",
          "Ex-tabagista",
          "Etilista",
          "Controle de PA domiciliar regular",
        ],
      },
      {
        titulo: "Exame Físico",
        campo: "exame_fisico",
        opcoes: [
          "Bom estado geral",
          "Lúcido e orientado",
          "Corado, hidratado",
          "Acianótico, anictérico",
          "Ausculta pulmonar sem alterações",
          "Ausculta cardíaca: BRNF 2T sem sopros",
          "Ausculta cardíaca: presença de sopro sistólico",
          "Abdome sem alterações",
          "Pulsos periféricos presentes e simétricos",
          "Membros inferiores: sem edema",
          "Membros inferiores: edema (+/4+)",
          "Fundo de olho sem alterações",
        ],
      },
      {
        titulo: "Sinais Vitais",
        campo: "sinais_vitais",
        opcoes: [
          "PA dentro da meta terapêutica",
          "PA acima da meta terapêutica",
          "PA em estágio 1 (140-159/90-99)",
          "PA em estágio 2 (160-179/100-109)",
          "PA em estágio 3 (≥180/≥110)",
          "FC normal",
          "Taquicardia",
          "Bradicardia",
          "IMC: eutrófico",
          "IMC: sobrepeso",
          "IMC: obesidade",
        ],
      },
      {
        titulo: "Avaliação",
        campo: "avaliacao",
        opcoes: [
          "HAS controlada",
          "HAS não controlada",
          "HAS resistente",
          "Risco cardiovascular baixo",
          "Risco cardiovascular moderado",
          "Risco cardiovascular alto",
          "Lesão de órgão-alvo presente",
          "Sem lesão de órgão-alvo",
          "Dislipidemia associada",
          "Diabetes associado",
        ],
      },
      {
        titulo: "Conduta",
        campo: "conduta",
        opcoes: [
          "Manutenção do tratamento atual",
          "Ajuste de dose do anti-hipertensivo",
          "Adição de novo anti-hipertensivo",
          "Troca de medicação",
          "Solicitação de exames de rotina (hemograma, função renal, eletrólitos, perfil lipídico, glicemia, urina I, ECG)",
          "Solicitação de ecocardiograma",
          "Solicitação de MAPA/MRPA",
          "Solicitação de fundo de olho",
          "Orientações sobre dieta hipossódica",
          "Orientações sobre atividade física",
          "Encaminhamento para cardiologista",
          "Encaminhamento para nutricionista",
          "Retorno em 30 dias",
          "Retorno em 60 dias",
          "Retorno em 90 dias",
        ],
      },
    ],
  },
  {
    id: "med_ap_diabetico",
    nome: "Diabético",
    descricao: "Acompanhamento de pacientes diabéticos",
    grupos: [
      {
        titulo: "Queixa Principal",
        campo: "queixa_principal",
        opcoes: [
          "Consulta de rotina",
          "Polidipsia",
          "Poliúria",
          "Perda de peso",
          "Turvação visual",
          "Formigamento em extremidades",
          "Ferida de difícil cicatrização",
          "Episódios de hipoglicemia",
          "Assintomático",
        ],
      },
      {
        titulo: "Adesão ao Tratamento",
        campo: "hda",
        opcoes: [
          "Uso regular da medicação",
          "Uso irregular da medicação",
          "Uso de insulina conforme prescrito",
          "Aplicação inadequada de insulina",
          "Automonitorização glicêmica regular",
          "Dieta para diabético mantida",
          "Dieta inadequada",
          "Prática de atividade física regular",
          "Sedentário",
          "Tabagista",
          "Etilista",
        ],
      },
      {
        titulo: "Exame Físico",
        campo: "exame_fisico",
        opcoes: [
          "Bom estado geral",
          "Lúcido e orientado",
          "Corado, hidratado",
          "Acianótico, anictérico",
          "Ausculta pulmonar sem alterações",
          "Ausculta cardíaca sem alterações",
          "Abdome sem alterações",
          "Membros inferiores: sem edema",
          "Membros inferiores: edema (+/4+)",
          "Pulsos periféricos presentes e simétricos",
          "Pulsos periféricos diminuídos",
          "Exame dos pés: sem alterações",
          "Exame dos pés: lesões tróficas",
          "Exame dos pés: sensibilidade preservada (monofilamento)",
          "Exame dos pés: sensibilidade diminuída",
          "Exame dos pés: calosidades",
          "Exame dos pés: micose interdigital",
        ],
      },
      {
        titulo: "Sinais Vitais",
        campo: "sinais_vitais",
        opcoes: [
          "PA dentro da normalidade",
          "PA elevada",
          "Glicemia capilar dentro da meta",
          "Glicemia capilar acima da meta",
          "Glicemia capilar abaixo de 70 (hipoglicemia)",
          "FC normal",
          "IMC: eutrófico",
          "IMC: sobrepeso",
          "IMC: obesidade",
          "Circunferência abdominal aumentada",
        ],
      },
      {
        titulo: "Avaliação",
        campo: "avaliacao",
        opcoes: [
          "DM2 controlado",
          "DM2 não controlado",
          "HbA1c dentro da meta (<7%)",
          "HbA1c acima da meta",
          "Nefropatia diabética",
          "Retinopatia diabética",
          "Neuropatia diabética",
          "Pé diabético",
          "HAS associada",
          "Dislipidemia associada",
          "Risco cardiovascular elevado",
        ],
      },
      {
        titulo: "Conduta",
        campo: "conduta",
        opcoes: [
          "Manutenção do tratamento atual",
          "Ajuste de dose do hipoglicemiante oral",
          "Adição de hipoglicemiante",
          "Início de insulinoterapia",
          "Ajuste de dose de insulina",
          "Solicitação de HbA1c",
          "Solicitação de perfil lipídico",
          "Solicitação de função renal e microalbuminúria",
          "Solicitação de fundo de olho",
          "Solicitação de ECG",
          "Orientações sobre dieta para diabético",
          "Orientações sobre cuidados com os pés",
          "Orientações sobre sinais de hipoglicemia",
          "Encaminhamento para endocrinologista",
          "Encaminhamento para oftalmologista",
          "Encaminhamento para nutricionista",
          "Retorno em 30 dias",
          "Retorno em 60 dias",
          "Retorno em 90 dias",
        ],
      },
    ],
  },
  {
    id: "med_ap_prenatal",
    nome: "Pré-natal",
    descricao: "Acompanhamento pré-natal de gestantes",
    grupos: [
      {
        titulo: "Queixa Principal",
        campo: "queixa_principal",
        opcoes: [
          "Consulta de pré-natal de rotina",
          "Náuseas e vômitos",
          "Dor lombar",
          "Edema em membros inferiores",
          "Cefaleia",
          "Sangramento vaginal",
          "Perda de líquido",
          "Diminuição dos movimentos fetais",
          "Contrações uterinas",
          "Queixas urinárias",
          "Assintomática",
        ],
      },
      {
        titulo: "Dados Obstétricos",
        campo: "hda",
        opcoes: [
          "Primigesta",
          "Multigesta",
          "DUM compatível com IG",
          "IG pelo USG",
          "Movimentos fetais presentes",
          "Movimentos fetais diminuídos",
          "Uso de ácido fólico",
          "Uso de sulfato ferroso",
          "Vacinação em dia",
          "Vacinação pendente",
          "Pré-natal de risco habitual",
          "Pré-natal de alto risco",
        ],
      },
      {
        titulo: "Exame Físico",
        campo: "exame_fisico",
        opcoes: [
          "Bom estado geral",
          "Corada, hidratada",
          "Mamas: sem alterações",
          "Ausculta cardíaca sem alterações",
          "Ausculta pulmonar sem alterações",
          "Abdome gravídico, compatível com IG",
          "Altura uterina adequada para IG",
          "Altura uterina abaixo do esperado",
          "BCF presente e regular",
          "BCF: taquicardia fetal",
          "BCF: bradicardia fetal",
          "Apresentação cefálica",
          "Apresentação pélvica",
          "Edema em MMII (+/4+)",
          "Sem edema",
          "Toque vaginal: colo fechado",
          "Toque vaginal: colo pérvio",
        ],
      },
      {
        titulo: "Sinais Vitais",
        campo: "sinais_vitais",
        opcoes: [
          "PA dentro da normalidade",
          "PA elevada",
          "Ganho de peso adequado",
          "Ganho de peso excessivo",
          "Ganho de peso insuficiente",
          "Temperatura normal",
          "FC normal",
          "Glicemia normal",
          "Glicemia alterada",
        ],
      },
      {
        titulo: "Avaliação",
        campo: "avaliacao",
        opcoes: [
          "Gestação de risco habitual, evolução adequada",
          "Gestação de alto risco",
          "Hipertensão gestacional",
          "Pré-eclâmpsia",
          "Diabetes gestacional",
          "Infecção urinária na gestação",
          "Anemia na gestação",
          "Ameaça de parto prematuro",
          "Restrição de crescimento fetal",
          "Gestação a termo",
        ],
      },
      {
        titulo: "Conduta",
        campo: "conduta",
        opcoes: [
          "Manutenção do pré-natal de rotina",
          "Solicitação de exames do 1º trimestre",
          "Solicitação de exames do 2º trimestre",
          "Solicitação de exames do 3º trimestre",
          "Solicitação de ultrassonografia obstétrica",
          "Prescrição de sulfato ferroso e ácido fólico",
          "Atualização vacinal",
          "Orientações sobre sinais de alerta",
          "Orientações sobre aleitamento materno",
          "Encaminhamento para pré-natal de alto risco",
          "Encaminhamento para maternidade de referência",
          "Retorno em 30 dias",
          "Retorno em 15 dias",
          "Retorno semanal",
        ],
      },
    ],
  },
  {
    id: "med_ap_puericultura",
    nome: "Puericultura",
    descricao: "Acompanhamento do crescimento e desenvolvimento infantil",
    grupos: [
      {
        titulo: "Motivo da Consulta",
        campo: "queixa_principal",
        opcoes: [
          "Consulta de puericultura de rotina",
          "Febre",
          "Tosse / coriza",
          "Diarreia",
          "Vômitos",
          "Inapetência",
          "Choro excessivo",
          "Dificuldade para amamentar",
          "Assintomático",
        ],
      },
      {
        titulo: "Alimentação e Desenvolvimento",
        campo: "hda",
        opcoes: [
          "Aleitamento materno exclusivo",
          "Aleitamento materno complementado",
          "Uso de fórmula infantil",
          "Alimentação complementar adequada para idade",
          "Alimentação inadequada para idade",
          "DNPM adequado para idade",
          "Atraso no DNPM",
          "Vacinação em dia",
          "Vacinação atrasada",
          "Sono adequado",
          "Eliminações fisiológicas normais",
        ],
      },
      {
        titulo: "Exame Físico",
        campo: "exame_fisico",
        opcoes: [
          "Bom estado geral, ativo, reativo",
          "Corado, hidratado",
          "Fontanela anterior normotensa",
          "Fontanela anterior abaulada",
          "Orofaringe sem alterações",
          "Otoscopia sem alterações",
          "Ausculta pulmonar sem alterações",
          "Ausculta cardíaca sem alterações",
          "Abdome sem alterações",
          "Genitália sem alterações",
          "Teste do olhinho: normal",
          "Teste da orelhinha: normal",
          "Teste do coraçãozinho: normal",
          "Teste do pezinho: realizado",
        ],
      },
      {
        titulo: "Antropometria",
        campo: "sinais_vitais",
        opcoes: [
          "Peso adequado para idade",
          "Peso abaixo do esperado",
          "Peso acima do esperado",
          "Estatura adequada para idade",
          "Estatura abaixo do esperado",
          "Perímetro cefálico adequado",
          "Perímetro cefálico alterado",
          "Curva de crescimento ascendente",
          "Curva de crescimento estacionária",
          "Curva de crescimento descendente",
        ],
      },
      {
        titulo: "Avaliação",
        campo: "avaliacao",
        opcoes: [
          "Crescimento e desenvolvimento adequados",
          "Risco nutricional",
          "Desnutrição",
          "Sobrepeso/obesidade infantil",
          "Atraso no desenvolvimento neuropsicomotor",
          "IVAS",
          "Otite média aguda",
          "Dermatite de fralda",
          "Anemia ferropriva",
        ],
      },
      {
        titulo: "Conduta",
        campo: "conduta",
        opcoes: [
          "Orientações sobre aleitamento materno",
          "Orientações sobre alimentação complementar",
          "Orientações sobre higiene e prevenção de acidentes",
          "Prescrição de suplementação de ferro profilática",
          "Prescrição de vitamina D",
          "Atualização do calendário vacinal",
          "Solicitação de exames de rotina",
          "Encaminhamento para especialista",
          "Encaminhamento para nutricionista",
          "Retorno conforme calendário de puericultura",
        ],
      },
    ],
  },
  {
    id: "med_ap_saude_mulher",
    nome: "Saúde da Mulher",
    descricao: "Consultas de saúde da mulher e ginecologia",
    grupos: [
      {
        titulo: "Motivo da Consulta",
        campo: "queixa_principal",
        opcoes: [
          "Coleta de citopatológico",
          "Planejamento familiar",
          "Irregularidade menstrual",
          "Dor pélvica",
          "Corrimento vaginal",
          "Sangramento vaginal anormal",
          "Sintomas climatéricos",
          "Mastalgia",
          "Consulta de rotina",
        ],
      },
      {
        titulo: "Antecedentes Ginecológicos",
        campo: "hda",
        opcoes: [
          "Menarca precoce/tardia",
          "Ciclos regulares",
          "Ciclos irregulares",
          "DUM informada",
          "Uso de método contraceptivo",
          "Não usa método contraceptivo",
          "Citopatológico anterior normal",
          "Citopatológico anterior alterado",
          "Mamografia anterior normal",
          "Mamografia anterior alterada",
          "G_P_A_ (informar paridade)",
          "Menopausa",
        ],
      },
      {
        titulo: "Exame Físico",
        campo: "exame_fisico",
        opcoes: [
          "Bom estado geral",
          "Mamas: sem nódulos palpáveis",
          "Mamas: nódulo palpável",
          "Mamas: sem descarga papilar",
          "Abdome sem alterações",
          "Especular: colo sem alterações",
          "Especular: colo com ectopia",
          "Especular: presença de corrimento",
          "Especular: coleta de citopatológico realizada",
          "Toque vaginal: útero em AVF, tamanho normal",
          "Toque vaginal: anexos livres",
        ],
      },
      {
        titulo: "Sinais Vitais",
        campo: "sinais_vitais",
        opcoes: ["PA normal", "PA elevada", "FC normal", "Peso aferido", "IMC calculado"],
      },
      {
        titulo: "Avaliação",
        campo: "avaliacao",
        opcoes: [
          "Exame ginecológico sem alterações",
          "Vulvovaginite",
          "Candidíase vulvovaginal",
          "Vaginose bacteriana",
          "IST",
          "Miomatose uterina",
          "Síndrome climatérica",
          "Amenorreia (investigar)",
          "Sangramento uterino anormal",
        ],
      },
      {
        titulo: "Conduta",
        campo: "conduta",
        opcoes: [
          "Coleta de citopatológico realizada",
          "Prescrição de tratamento para vulvovaginite",
          "Solicitação de mamografia",
          "Solicitação de USG pélvica/transvaginal",
          "Prescrição de método contraceptivo",
          "Orientações sobre planejamento familiar",
          "Orientações sobre prevenção de ISTs",
          "Solicitação de sorologias",
          "Encaminhamento para ginecologista",
          "Encaminhamento para mastologista",
          "Retorno com resultado de exames",
        ],
      },
    ],
  },
  {
    id: "med_ap_saude_crianca",
    nome: "Saúde da Criança",
    descricao: "Atendimento pediátrico na APS",
    grupos: [
      {
        titulo: "Queixa Principal",
        campo: "queixa_principal",
        opcoes: [
          "Febre",
          "Tosse e coriza",
          "Dor de ouvido",
          "Dor de garganta",
          "Diarreia",
          "Vômitos",
          "Dor abdominal",
          "Exantema / lesões de pele",
          "Dificuldade respiratória",
          "Inapetência",
          "Consulta de rotina",
        ],
      },
      {
        titulo: "História",
        campo: "hda",
        opcoes: [
          "Início há menos de 24 horas",
          "Início há 2-5 dias",
          "Início há mais de 5 dias",
          "Febre aferida em casa",
          "Uso de medicação em domicílio",
          "Alimentação preservada",
          "Alimentação reduzida",
          "Aceitação hídrica boa",
          "Vacinação em dia",
          "Vacinação atrasada",
          "Contato com pessoas doentes",
        ],
      },
      {
        titulo: "Exame Físico",
        campo: "exame_fisico",
        opcoes: [
          "Bom estado geral, ativo, reativo",
          "Regular estado geral, hipoativo",
          "Corado, hidratado",
          "Descorado",
          "Desidratado",
          "Orofaringe: hiperemiada",
          "Orofaringe: presença de exsudato",
          "Otoscopia: membrana timpânica hiperemiada",
          "Otoscopia: sem alterações",
          "Ausculta pulmonar: sem alterações",
          "Ausculta pulmonar: sibilos",
          "Ausculta pulmonar: estertores",
          "Abdome: sem alterações",
          "Abdome: doloroso à palpação",
          "Pele: sem lesões",
          "Pele: exantema",
        ],
      },
      {
        titulo: "Sinais Vitais",
        campo: "sinais_vitais",
        opcoes: [
          "Temperatura normal",
          "Febre",
          "FC adequada para idade",
          "FR adequada para idade",
          "SatO₂ ≥ 95%",
          "SatO₂ < 95%",
          "Peso aferido",
        ],
      },
      {
        titulo: "Avaliação",
        campo: "avaliacao",
        opcoes: [
          "IVAS (resfriado comum)",
          "Faringoamigdalite",
          "Otite média aguda",
          "Pneumonia",
          "Bronquiolite",
          "Asma / crise de sibilância",
          "Gastroenterite aguda",
          "Parasitose intestinal",
          "Dermatite",
          "Impetigo",
          "Infecção do trato urinário",
        ],
      },
      {
        titulo: "Conduta",
        campo: "conduta",
        opcoes: [
          "Prescrição medicamentosa conforme diagnóstico",
          "Terapia de reidratação oral",
          "Orientações sobre sinais de alarme",
          "Orientações sobre hidratação e alimentação",
          "Solicitação de exames",
          "Encaminhamento para urgência pediátrica",
          "Encaminhamento para especialista",
          "Retorno em 48 horas",
          "Retorno em 7 dias",
          "Retorno se piora",
        ],
      },
    ],
  },
  {
    id: "med_ap_saude_idoso",
    nome: "Saúde do Idoso",
    descricao: "Acompanhamento geriátrico na APS",
    grupos: [
      {
        titulo: "Queixa Principal",
        campo: "queixa_principal",
        opcoes: [
          "Consulta de rotina",
          "Tontura / vertigem",
          "Dor articular",
          "Quedas recorrentes",
          "Esquecimento / perda de memória",
          "Insônia",
          "Tristeza / desânimo",
          "Incontinência urinária",
          "Constipação",
          "Dificuldade para caminhar",
          "Dor crônica",
          "Polifarmácia",
        ],
      },
      {
        titulo: "Avaliação Geriátrica",
        campo: "hda",
        opcoes: [
          "Independente para AVDs básicas",
          "Dependente parcial para AVDs básicas",
          "Dependente total para AVDs básicas",
          "Independente para AVDs instrumentais",
          "Dependente para AVDs instrumentais",
          "Marcha estável",
          "Marcha instável / uso de dispositivo auxiliar",
          "Cognição preservada",
          "Declínio cognitivo leve",
          "Suporte familiar adequado",
          "Suporte familiar insuficiente",
          "Risco de queda identificado",
          "Polifarmácia (≥5 medicamentos)",
        ],
      },
      {
        titulo: "Exame Físico",
        campo: "exame_fisico",
        opcoes: [
          "Bom estado geral",
          "Regular estado geral",
          "Lúcido e orientado",
          "Confuso / desorientado",
          "Corado, hidratado",
          "Descorado",
          "Ausculta pulmonar sem alterações",
          "Ausculta cardíaca sem alterações",
          "Abdome sem alterações",
          "Membros inferiores: sem edema",
          "Membros inferiores: edema",
          "Articulações: sem sinais inflamatórios",
          "Articulações: com sinais inflamatórios",
          "Força muscular preservada",
          "Sarcopenia",
          "Pele: íntegra",
          "Pele: lesões",
        ],
      },
      {
        titulo: "Sinais Vitais",
        campo: "sinais_vitais",
        opcoes: [
          "PA dentro da meta",
          "PA elevada",
          "Hipotensão ortostática",
          "FC normal",
          "Glicemia normal",
          "Glicemia alterada",
          "IMC: eutrófico",
          "IMC: baixo peso",
          "IMC: sobrepeso",
          "Mini Mental (MEEM): dentro da normalidade",
          "Mini Mental (MEEM): alterado",
        ],
      },
      {
        titulo: "Avaliação",
        campo: "avaliacao",
        opcoes: [
          "Idoso saudável / envelhecimento ativo",
          "Fragilidade",
          "Pré-fragilidade",
          "Risco de queda",
          "Declínio cognitivo",
          "Depressão geriátrica",
          "Polifarmácia — revisão necessária",
          "Osteoartrose",
          "Osteoporose",
          "HAS",
          "DM2",
          "Incontinência urinária",
        ],
      },
      {
        titulo: "Conduta",
        campo: "conduta",
        opcoes: [
          "Manutenção do tratamento",
          "Revisão e reconciliação medicamentosa",
          "Desprescrição de medicamento inapropriado",
          "Solicitação de exames de rotina",
          "Solicitação de densitometria óssea",
          "Aplicação de escala geriátrica (GDS, MEEM, Katz, Lawton)",
          "Orientações sobre prevenção de quedas",
          "Orientações sobre atividade física adaptada",
          "Encaminhamento para fisioterapia",
          "Encaminhamento para geriatria",
          "Encaminhamento para psicólogo",
          "Encaminhamento para nutricionista",
          "Retorno em 30 dias",
          "Retorno em 60 dias",
          "Retorno em 90 dias",
        ],
      },
    ],
  },
  {
    id: "med_ap_tuberculose",
    nome: "Tuberculose",
    descricao: "Acompanhamento de pacientes com tuberculose",
    grupos: [
      {
        titulo: "Queixa Principal",
        campo: "queixa_principal",
        opcoes: [
          "Consulta de acompanhamento TB",
          "Tosse produtiva",
          "Hemoptise",
          "Febre vespertina",
          "Sudorese noturna",
          "Perda de peso",
          "Inapetência",
          "Fadiga",
          "Dispneia",
          "Assintomático (em tratamento)",
        ],
      },
      {
        titulo: "Adesão ao Tratamento",
        campo: "hda",
        opcoes: [
          "TDO (Tratamento Diretamente Observado) regular",
          "TDO irregular",
          "Fase intensiva do tratamento",
          "Fase de manutenção do tratamento",
          "Sem efeitos adversos",
          "Efeitos adversos: náuseas/vômitos",
          "Efeitos adversos: icterícia",
          "Efeitos adversos: neuropatia periférica",
          "Efeitos adversos: dor articular",
          "Efeitos adversos: alteração visual",
          "Contatos investigados",
          "Contatos pendentes de investigação",
        ],
      },
      {
        titulo: "Exame Físico",
        campo: "exame_fisico",
        opcoes: [
          "Bom estado geral",
          "Regular estado geral",
          "Emagrecido",
          "Corado / Descorado",
          "Ausculta pulmonar: MV+ sem RA",
          "Ausculta pulmonar: estertores em ápice",
          "Ausculta pulmonar: MV diminuído",
          "Abdome: hepatomegalia",
          "Abdome: sem alterações",
          "Linfonodos: sem linfonodomegalia",
          "Linfonodos: linfonodomegalia",
          "Pele: sem icterícia",
          "Pele: ictérico",
        ],
      },
      {
        titulo: "Sinais Vitais",
        campo: "sinais_vitais",
        opcoes: [
          "Afebril",
          "Febril",
          "PA normal",
          "FC normal",
          "Peso atual (comparar com anterior)",
          "Ganho de peso em relação à consulta anterior",
          "Perda de peso em relação à consulta anterior",
          "SatO₂ normal",
        ],
      },
      {
        titulo: "Avaliação",
        campo: "avaliacao",
        opcoes: [
          "TB pulmonar em tratamento — boa evolução",
          "TB pulmonar em tratamento — resposta insatisfatória",
          "TB extrapulmonar",
          "Efeito adverso menor",
          "Efeito adverso maior — avaliar suspensão",
          "Baciloscopia de controle negativa",
          "Baciloscopia de controle positiva",
          "Coinfecção TB-HIV",
          "TB multirresistente (suspeita)",
        ],
      },
      {
        titulo: "Conduta",
        campo: "conduta",
        opcoes: [
          "Manutenção do esquema RIPE",
          "Transição para fase de manutenção (RI)",
          "Solicitação de baciloscopia de controle",
          "Solicitação de cultura e TSA",
          "Solicitação de função hepática",
          "Solicitação de radiografia de tórax",
          "Solicitar teste de HIV",
          "Prescrição de piridoxina (vitamina B6)",
          "Manejo de efeito adverso",
          "Busca ativa de contatos",
          "Notificação / atualização SINAN",
          "Encaminhamento para referência de TB",
          "Retorno mensal",
        ],
      },
    ],
  },
  {
    id: "med_ap_hanseniase",
    nome: "Hanseníase",
    descricao: "Acompanhamento de pacientes com hanseníase",
    grupos: [
      {
        titulo: "Queixa Principal",
        campo: "queixa_principal",
        opcoes: [
          "Consulta de acompanhamento",
          "Manchas na pele com alteração de sensibilidade",
          "Dormência em mãos/pés",
          "Fraqueza muscular",
          "Dor em trajeto nervoso",
          "Piora das lesões cutâneas",
          "Reação hansênica",
          "Assintomático (em tratamento)",
        ],
      },
      {
        titulo: "Adesão ao Tratamento",
        campo: "hda",
        opcoes: [
          "PQT regular (dose supervisionada em dia)",
          "PQT irregular",
          "Classificação: Paucibacilar (PB)",
          "Classificação: Multibacilar (MB)",
          "Mês ___/6 (PB) ou ___/12 (MB) de tratamento",
          "Sem efeitos adversos",
          "Efeitos adversos: anemia",
          "Efeitos adversos: alteração de cor da pele",
          "Efeitos adversos: náuseas",
          "Contatos examinados",
          "Contatos pendentes",
        ],
      },
      {
        titulo: "Exame Físico / Dermatoneurológico",
        campo: "exame_fisico",
        opcoes: [
          "Bom estado geral",
          "Lesões cutâneas: estáveis",
          "Lesões cutâneas: em regressão",
          "Lesões cutâneas: novas lesões",
          "Sensibilidade térmica preservada",
          "Sensibilidade térmica diminuída/ausente",
          "Sensibilidade dolorosa preservada",
          "Sensibilidade dolorosa diminuída/ausente",
          "Sensibilidade tátil preservada",
          "Sensibilidade tátil diminuída/ausente",
          "Nervos periféricos: sem espessamento",
          "Nervos periféricos: espessamento",
          "Força muscular preservada",
          "Garra ulnar / garra mediana",
          "Mão caída / pé caído",
          "Olhos: sem alterações",
          "Olhos: lagoftalmo",
        ],
      },
      {
        titulo: "Grau de Incapacidade",
        campo: "sinais_vitais",
        opcoes: [
          "Grau 0: sem comprometimento neural",
          "Grau 1: diminuição de sensibilidade",
          "Grau 2: deformidade visível / incapacidade",
          "Avaliação de mãos: sem alterações",
          "Avaliação de mãos: alterações presentes",
          "Avaliação de pés: sem alterações",
          "Avaliação de pés: alterações presentes",
          "Avaliação de olhos: sem alterações",
          "Avaliação de olhos: alterações presentes",
        ],
      },
      {
        titulo: "Avaliação",
        campo: "avaliacao",
        opcoes: [
          "Hanseníase PB em tratamento — boa evolução",
          "Hanseníase MB em tratamento — boa evolução",
          "Resposta terapêutica insatisfatória",
          "Reação tipo 1 (reversa)",
          "Reação tipo 2 (eritema nodoso hansênico)",
          "Neurite",
          "Incapacidade instalada",
          "Alta por cura (critérios preenchidos)",
        ],
      },
      {
        titulo: "Conduta",
        campo: "conduta",
        opcoes: [
          "Manutenção da PQT",
          "Dose supervisionada administrada",
          "Manejo de reação hansênica com prednisona",
          "Manejo de reação tipo 2 com talidomida",
          "Avaliação neurológica simplificada",
          "Avaliação de grau de incapacidade",
          "Orientações sobre autocuidado",
          "Exercícios para prevenção de incapacidades",
          "Solicitação de hemograma de controle",
          "Exame de contatos domiciliares",
          "Aplicação de BCG em contatos",
          "Notificação / atualização SINAN",
          "Encaminhamento para referência",
          "Retorno mensal para dose supervisionada",
        ],
      },
    ],
  },
];

export default medicoAtencaoPrimaria;